// Generated by CoffeeScript 1.10.0
(function() {
  var button, toggleFunction, youtubeSidebar;

  youtubeSidebar = document.querySelector('#watch7-sidebar-contents');

  button = document.createElement('div');

  button.classList.add('related-toggler');

  button.innerText = "Click to Display/Hide Related Videos";

  toggleFunction = function() {
    if (youtubeSidebar.classList.contains('ola-show')) {
      return youtubeSidebar.classList.remove('ola-show');
    } else {
      return youtubeSidebar.classList.add('ola-show');
    }
  };

  button.addEventListener('click', toggleFunction);

  youtubeSidebar.parentElement.insertBefore(button, youtubeSidebar);

}).call(this);
